// This file is generated by Astro DB
declare module 'astro:db' {
<<<<<<< HEAD
	export const users: import("@astrojs/db/runtime").Table<
		"users",
		{"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"users","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"users","primaryKey":false,"optional":false}}}
	>;
=======

>>>>>>> 0300e722a1287109d9083dd4060cb2e9fdbeb789
}
